import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Data',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: FirebaseDataScreen(),
    );
  }
}

class FirebaseDataScreen extends StatefulWidget {
  @override
  _FirebaseDataScreenState createState() => _FirebaseDataScreenState();
}

class _FirebaseDataScreenState extends State<FirebaseDataScreen> {
  final DatabaseReference _databaseRef = FirebaseDatabase.instance.ref();
  List<String> childrenData = []; // List to store child data as strings

  @override
  void initState() {
    super.initState();
    _fetchData();
  }

  void _fetchData() {
    _databaseRef.onValue.listen((event) {
      final data = event.snapshot.value;
      print("Raw Firebase data: $data");

      if (data == null) {
        print("No data found.");
        setState(() {
          childrenData = [];
        });
        return;
      }

      if (data is Map<dynamic, dynamic>) {
        List<String> loadedData = [];

        data.forEach((key, value) {
          print("🔹 Child Key: $key - Data: $value");
          // Adding the key-value pair as a string to the list
          loadedData.add("Key: $key, Value: $value");
        });

        setState(() {
          childrenData = loadedData; // Update the list to trigger UI rebuild
        });

      } else {
        print("Unexpected Firebase structure: $data");
      }
    }, onError: (error) {
      print("Database Error: $error");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Firebase Data - Realtime Scans")),
      body: childrenData.isEmpty
          ? Center(child: Text("No data found!"))
          : ListView.builder(
        itemCount: childrenData.length,
        itemBuilder: (context, index) {
          return Card(  // Wrap the ListTile in a Card widget to surround it with a box
            elevation: 2,  // Optional: Adds a shadow effect
            margin: EdgeInsets.symmetric(vertical: 5, horizontal: 10),  // Optional: Adds margin around the card
            child: ListTile(
              title: Text(childrenData[index].replaceFirst("Key: ", "").replaceFirst("Value:","     ")),  // Omit the word "Key"
            ),
          );
        },
      ),
    );
  }
}
